import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { Loader2, AlertCircle } from 'lucide-react';

interface PortfolioData {
  html_code: string;
  css_code: string;
  slug: string;
}

export const PublicPortfolio: React.FC = () => {
  const { slug } = useParams<{ slug: string }>();
  const [portfolio, setPortfolio] = useState<PortfolioData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchPublicPortfolio = async () => {
      try {
        const response = await fetch(`http://localhost:5000/api/portfolio/${slug}`, {
          headers: {
            Accept: 'application/json',
          },
        });

        if (response.ok) {
          const data = await response.json();
          setPortfolio(data);
        } else {
          setError('This portfolio is either private, not published, or does not exist.');
        }
      } catch (err) {
        console.error('Failed to load portfolio:', err);
        setError('Network connection failed. Could not load portfolio site.');
      } finally {
        setLoading(false);
      }
    };

    if (slug) {
      fetchPublicPortfolio();
    }
  }, [slug]);

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0B0F14] flex flex-col items-center justify-center">
        <Loader2 className="w-8 h-8 text-[#EACEAA] animate-spin" />
        <p className="text-xs text-slate-400 mt-4 font-bold tracking-wider font-mono uppercase">Fetching Web Layout...</p>
      </div>
    );
  }

  if (error || !portfolio) {
    return (
      <div className="min-h-screen bg-[#0B0F14] flex flex-col items-center justify-center p-4">
        <div className="hud-card max-w-md p-8 border-red-500/20 bg-[#34150F]/20 text-center space-y-4">
          <AlertCircle className="w-12 h-12 text-red-400 mx-auto" />
          <h2 className="text-xl font-black text-white tracking-tight">Portfolio Unavailable</h2>
          <p className="text-xs text-slate-400 leading-relaxed font-medium">{error || 'Unable to locate portfolio slug.'}</p>
          <a
            href="/"
            className="inline-block px-5 py-2.5 rounded-xl border border-white/10 bg-white/[0.03] hover:bg-white/[0.08] text-xs font-bold text-slate-300 uppercase tracking-wider transition-colors"
          >
            Return to Homepage
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0B0F14] text-white">
      {/* Inject custom CSS generated by portfolio compiler */}
      {portfolio.css_code && <style>{portfolio.css_code}</style>}

      {/* Render custom compiled HTML */}
      <div 
        dangerouslySetInnerHTML={{ __html: portfolio.html_code }}
      />
    </div>
  );
};
